### ISSUE TITLE
PDF export no longer works in Pentaho platform.

### ISSUE THREAD

**Issue by mysticfall** [mysticfall/pivot4j#139]
It seems Pentaho platform bundles its own version of FOP, and throws following exception when PDF export is requested : 

```
Caused by: java.lang.ClassCastException: org.apache.fop.render.pdf.PDFRendererMaker cannot be cast to org.apache.fop.render.AbstractRendererMaker
        at org.apache.fop.render.RendererFactory.discoverRenderers(RendererFactory.java:425)
        at org.apache.fop.render.RendererFactory.<init>(RendererFactory.java:61)
        at org.apache.fop.apps.FopFactory.<init>(FopFactory.java:179)
        at org.apache.fop.apps.FopFactory.newInstance(FopFactory.java:190)
        at org.pivot4j.ui.fop.FopExporter.createFopFactory(FopExporter.java:271)
        at org.pivot4j.ui.fop.FopExporter.startRender(FopExporter.java:320)
        at org.pivot4j.ui.fop.FopExporter.startRender(FopExporter.java:40)
        at org.pivot4j.ui.table.TableRenderer.render(TableRenderer.java:439)
        at org.pivot4j.analytics.ui.PivotExportHandler.exportPdf(PivotExportHandler.java:406)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.apache.el.parser.AstValue.invoke(AstValue.java:191) 
```
- Related forum post : https://groups.google.com/d/msg/pivot4j-list/rVCXdmrmwxE/1Jke8mwBqz4J

**Comment by mzko** [comment]
What about "when exporting to pdf had problems with Russian encoding - instead of Russian letters were ###" ? This issue is not fixed yet (
