### ISSUE TITLE
Column Selection in Drill Window does not work = drill functionality does not work

### ISSUE THREAD

**Issue by szymic1** [mysticfall/pivot4j#200]
Pentaho 6.1+ Pivot 1.0 

Column selection functionality in Drill Window does not work - when I select few columns and press "Apply" new columns appear but when I unmark column and press "Apply" column is displayed and I cannot modify any column selection. **With this error "Drill" functionality is useless and work randomly** - I cannot create export! On the screen below column "ILOSC POJAZDOW NA KREDYT" is displayed but unmark this column and I pressed "Apply" (table does not responded to changing configurartion).

![2016-05-05 11_57_55-pivot4j](https://cloud.githubusercontent.com/assets/15525927/15041077/8d50e36c-12b9-11e6-8ca9-ceea6e8e39ef.png)

**Comment by szymic1** [comment]
I've notice that first column selection after opening "Drill Windows" works but second attempt to press 'Apply" always does not work :(

**Comment by mysticfall** [comment]
Sorry to hear that you have such an issue, but I failed to reproduce the problem you mentioned.

Does it occur only with a specific data source? Or can you reproduce it with the FoodMart database?

Also, please check the log file and see if you see any error messages when it happens.

**Comment by szymic1** [comment]
Hi
I make a test usign following configuration:
- Windows 10 (Polish version) but the 
- Java 1.8.0_91 64bit 
- Pentaho CE 6.1.0.1.196
- Pivot4J (instaled using Pentaho Market)

these same problem appears on Debian+Java 1.7 and happens always.

Here you have movie  how to reproduce bug  https://www.youtube.com/watch?v=V3KVA0_EGeM

After installation I simply login to server and I've made a test in this link you can see what I've done during this test. As you can see on movie after initial 'drill window' opening nothing is 'checked' in "Column Selection" what is first bug after choosing "Quantity" and "Sales" two column have been shown, I've deselected "Sales" and pressed Apply - and now nothing change :(

**Comment by mysticfall** [comment]
Thanks for the detailed instruction. I was able to reproduce a similar problem and I'm on investigating right now.

The relevant stacktrace was: 
```
mondrian.olap.MondrianException: Mondrian Error:Unknown member type in DRILLTHROUGH operation.
        at mondrian.rolap.RolapAggregationManager.addNonConstrainingColumns(RolapAggregationManager.java:456)
        at mondrian.rolap.RolapAggregationManager.makeCellRequest(RolapAggregationManager.java:324)
        at mondrian.rolap.RolapAggregationManager.makeDrillThroughRequest(RolapAggregationManager.java:92)
        at mondrian.rolap.RolapCell.getDrillThroughSQL(RolapCell.java:124)
        at mondrian.rolap.RolapCell.drillThroughInternal(RolapCell.java:464)
        at mondrian.olap4j.MondrianOlap4jCell.drillThroughInternal(MondrianOlap4jCell.java:165)
        at mondrian.olap4j.MondrianOlap4jStatement.executeQuery2(MondrianOlap4jStatement.java:98)
        at mondrian.olap4j.MondrianOlap4jStatement.executeQuery(MondrianOlap4jStatement.java:65)
        at org.pivot4j.transform.impl.DrillThroughImpl.performDrillThroughMdx(DrillThroughImpl.java:189)
        at org.pivot4j.transform.impl.DrillThroughImpl.drillThrough(DrillThroughImpl.java:77)
        at org.pivot4j.analytics.ui.DrillThroughDataModel.execute(DrillThroughDataModel.java:163)
        at org.pivot4j.analytics.ui.DrillThroughDataModel.load(DrillThroughDataModel.java:184)
        at org.primefaces.component.datatable.DataTable.loadLazyData(DataTable.java:976)
        at org.primefaces.component.datatable.DataTableRenderer.preRender(DataTableRenderer.java:95)
        at org.primefaces.component.datatable.DataTableRenderer.encodeEnd(DataTableRenderer.java:83)
```

**Comment by mysticfall** [comment]
Finally, I was able to track down the root cause of this problem. I'll deploy a new snapshot containing  the fix now.

Thanks for your patience!

**Comment by szymic1** [comment]
Hi, I've installed (using update n marketplace in Pentaho 6.1, is it right way to install?) and now it works a little better but bug still exists.  To be honest there are 3 bugs.

First bug:   https://youtu.be/O6MxiJ7CDHw
as you see it works with measures but when you want marked/unmarked rows related to dimension numbers of columns does not change :(

Second bug: https://youtu.be/wCORl2yp4LY
When you close Drill Window and you open once again this window and you check only one column two columns are displayed :(

Third bug: It is not severe bug but in my opinion should be fixed  - when you open Drill Window parts of messaures/dimension are unmarked but  columns are displayed.
