### ISSUE TITLE
Bug in use same dimension in cube with SSAS

### ISSUE THREAD

**Issue by mauriciofh** [mysticfall/pivot4j#212]
Hi.

Firstly thank you for keeping this product, and would like to report a problem with Microsoft SSAS cubes.

I'm using Microsoft's AdventureWorksDW2012 to show you.
Dimensions with name "Ship Date", "Delivery Date", and Date share the same Date dimension however use different keys and names, only this.
When using them in the Pivot structure the application does not mount right and when using the magnifying glass of the dimension to change values, several errors occur. The following image.

![image](https://user-images.githubusercontent.com/29278537/26936426-12be9c68-4c45-11e7-8167-f04db3005b70.png)

Errors

![image](https://user-images.githubusercontent.com/29278537/26936519-50e2e71a-4c45-11e7-8923-85637ee00aa7.png)

**Comment by mysticfall** [comment]
I'm afraid if it might be hard to debug such an issue without being able to reproduce it. However, there's a chance that we can get some hints if you could post the whole stacktrace when it happens.

Please check the log file and see if you can find relevant stacktrace and post it the whole message.

**Comment by Pritsch** [comment]
Hello!

this is the logs:

> 09:37:31.070 DEBUG [ViewStateHolder] - Checking for abandoned view states for se
ssion : AE3947086F6B1DDDE70CBC218B82535E
09:37:31.070 DEBUG [ViewStateHolder] - Current view state count for session : 1
09:38:05.468 DEBUG [ViewStateHolder] - Received a keep alive request : org.pivot4j.analytics.state.ViewState@5ef0fb91[id=d2e30d06-7cb5-44bb-8abf-dd558d9f7798,name=Sem T+¡tulo(1),connectionInfo=org.pivot4j.analytics.datasource.ConnectionInfo@50ae94d0[cubeName=Despesas - TOTAL,catalogName=Encosta]]
09:38:11.726 ERROR [Pivot4JExceptionHandler] - Ocorreu uma exce+º+úo n+úo trat+ível
org.apache.myfaces.view.facelets.el.ContextAwareELException: javax.el.ELException: java.lang.IllegalArgumentException: Cannot find the specified hierarchyon any axis.
        at org.apache.myfaces.view.facelets.el.ContextAwareTagMethodExpression.invoke(ContextAwareTagMethodExpression.java:108) ~[myfaces-impl-2.2.3.jar:2.2.3]
        at org.apache.myfaces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:74) ~[myfaces-impl-2.2.3.jar:2.2.3]
        at javax.faces.component.UICommand.broadcast(UICommand.java:120) ~[myfaces-api-2.2.3.jar:2.2.3]
        at javax.faces.component.UIViewRoot._broadcastAll(UIViewRoot.java:1172) ~[myfaces-api-2.2.3.jar:2.2.3]
        at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:365) ~[myfaces-api-2.2.3.jar:2.2.3]
        at javax.faces.component.UIViewRoot._process(UIViewRoot.java:1656) ~[myfaces-api-2.2.3.jar:2.2.3]
        at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:862) ~[myfaces-api-2.2.3.jar:2.2.3]
        at org.apache.myfaces.lifecycle.InvokeApplicationExecutor.execute(InvokeApplicationExecutor.java:42) ~[myfaces-impl-2.2.3.jar:2.2.3]
        at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:196) [myfaces-impl-2.2.3.jar:2.2.3]
        at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:143) [myfaces-impl-2.2.3.jar:2.2.3]
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:198) [myfaces-api-2.2.3.jar:2.2.3]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [catalina.jar:7.0.78]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.78]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat7-websocket.jar:7.0.78]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.78]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.78]
        at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:67) [log4j-web-2.0.2.jar:2.0.2]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.78]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.78]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218) [catalina.jar:7.0.78]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110) [catalina.jar:7.0.78]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506) [catalina.jar:7.0.78]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169) [catalina.jar:7.0.78]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [catalina.jar:7.0.78]
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962) [catalina.jar:7.0.78]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina.jar:7.0.78]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445) [catalina.jar:7.0.78]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115) [tomcat-coyote.jar:7.0.78]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637) [tomcat-coyote.jar:7.0.78]
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318) [tomcat-coyote.jar:7.0.78]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_131]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote.jar:7.0.78]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: javax.el.ELException: java.lang.IllegalArgumentException: Cannot find the specified hierarchy on any axis.
        at org.apache.el.parser.AstValue.invoke(AstValue.java:292) ~[jasper-el.jar:7.0.78]
        at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:273) ~[jasper-el.jar:7.0.78]
        at org.apache.myfaces.view.facelets.el.ContextAwareTagMethodExpression.invoke(ContextAwareTagMethodExpression.java:96) ~[myfaces-impl-2.2.3.jar:2.2.3]
        ... 33 more
Caused by: java.lang.IllegalArgumentException: Cannot find the specified hierarchy on any axis.
        at org.pivot4j.transform.impl.PlaceMembersOnAxesImpl.placeMembers(PlaceMembersOnAxesImpl.java:70) ~[pivot4j-core-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.pivot4j.analytics.ui.MemberSelectionHandler.apply(MemberSelectionHandler.java:198) ~[classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
        at org.apache.el.parser.AstValue.invoke(AstValue.java:279) ~[jasper-el.jar:7.0.78]
        at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:273) ~[jasper-el.jar:7.0.78]
        at org.apache.myfaces.view.facelets.el.ContextAwareTagMethodExpression.invoke(ContextAwareTagMethodExpression.java:96) ~[myfaces-impl-2.2.3.jar:2.2.3]
        ... 33 more
09:38:31.078 DEBUG [ViewStateHolder] - Checking for abandoned view states for session : AE3947086F6B1DDDE70CBC218B82535E
09:38:31.078 DEBUG [ViewStateHolder] - Current view state count for session : 1
