### ISSUE TITLE
Error reading 'editable' on type org.pivot4j.analytics.ui.ViewHandler

### ISSUE THREAD

**Issue by GisDeng** [mysticfall/pivot4j#236]
when i start the project, and  choose Cube, but the Cube Structure is missing ,and appear some bug
16:21:22.640 ERROR [Pivot4JExceptionHandler] - Unhandled exception has occurred
org.apache.myfaces.view.facelets.el.ContextAwareELException: javax.el.ELException: Error reading 'editable' on type org.pivot4j.analytics.ui.ViewHandler
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:104) ~[myfaces-impl-2.2.3.jar:2.2.3]
	at javax.faces.component._DeltaStateHelper.eval(_DeltaStateHelper.java:377) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponentBase.isRendered(UIComponentBase.java:1211) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponent.isVisitable(UIComponent.java:348) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1011) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191) ~[myfaces-api-2.2.3.jar:2.2.3]
	at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartialExecute(PartialViewContextImpl.java:430) ~[myfaces-impl-2.2.3.jar:2.2.3]
	at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:411) ~[myfaces-impl-2.2.3.jar:2.2.3]
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:60) ~[primefaces-5.3.jar:5.3]
	at javax.faces.component.UIViewRoot$ApplyRequestValuesPhaseProcessor.process(UIViewRoot.java:1769) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIViewRoot._process(UIViewRoot.java:1653) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:869) ~[myfaces-api-2.2.3.jar:2.2.3]
	at org.apache.myfaces.lifecycle.ApplyRequestValuesExecutor.execute(ApplyRequestValuesExecutor.java:42) ~[myfaces-impl-2.2.3.jar:2.2.3]
	at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:196) [myfaces-impl-2.2.3.jar:2.2.3]
	at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:143) [myfaces-impl-2.2.3.jar:2.2.3]
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:198) [myfaces-api-2.2.3.jar:2.2.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.47]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) [tomcat7-websocket.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [catalina.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.47]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:67) [log4j-web-2.0.2.jar:2.0.2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [catalina.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.47]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.47]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.47]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [catalina.jar:7.0.47]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.47]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100) [catalina.jar:7.0.47]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953) [catalina.jar:7.0.47]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.47]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [catalina.jar:7.0.47]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041) [tomcat-coyote.jar:7.0.47]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603) [tomcat-coyote.jar:7.0.47]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310) [tomcat-coyote.jar:7.0.47]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: javax.el.ELException: Error reading 'editable' on type org.pivot4j.analytics.ui.ViewHandler
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:98) ~[el-api.jar:2.2.FR]
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:67) ~[el-api.jar:2.2.FR]
	at org.apache.myfaces.el.unified.resolver.FacesCompositeELResolver.getValue(FacesCompositeELResolver.java:179) ~[myfaces-impl-2.2.3.jar:2.2.3]
	at org.apache.el.parser.AstValue.getValue(AstValue.java:183) ~[jasper-el.jar:7.0.47]
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:185) ~[jasper-el.jar:7.0.47]
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:96) ~[myfaces-impl-2.2.3.jar:2.2.3]
	... 43 more
Caused by: java.lang.NullPointerException
	at org.pivot4j.analytics.ui.ViewHandler.isEditable(ViewHandler.java:804) ~[ViewHandler.class:?]
	at sun.reflect.GeneratedMethodAccessor89.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:87) ~[el-api.jar:2.2.FR]
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:67) ~[el-api.jar:2.2.FR]
	at org.apache.myfaces.el.unified.resolver.FacesCompositeELResolver.getValue(FacesCompositeELResolver.java:179) ~[myfaces-impl-2.2.3.jar:2.2.3]
	at org.apache.el.parser.AstValue.getValue(AstValue.java:183) ~[jasper-el.jar:7.0.47]
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:185) ~[jasper-el.jar:7.0.47]
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:96) ~[myfaces-impl-2.2.3.jar:2.2.3]
	... 43 more
16:21:22.642 ERROR [Pivot4JExceptionHandler] - Unhandled exception has occurred
org.apache.myfaces.view.facelets.el.ContextAwareELException: javax.el.ELException: Error reading 'editable' on type org.pivot4j.analytics.ui.ViewHandler
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:104) ~[myfaces-impl-2.2.3.jar:2.2.3]
	at javax.faces.component._DeltaStateHelper.eval(_DeltaStateHelper.java:377) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponentBase.isRendered(UIComponentBase.java:1211) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponent.isVisitable(UIComponent.java:348) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1011) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191) ~[myfaces-api-2.2.3.jar:2.2.3]
	at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartialExecute(PartialViewContextImpl.java:430) ~[myfaces-impl-2.2.3.jar:2.2.3]
	at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:411) ~[myfaces-impl-2.2.3.jar:2.2.3]
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:60) ~[primefaces-5.3.jar:5.3]
	at javax.faces.component.UIViewRoot$ProcessValidatorPhaseProcessor.process(UIViewRoot.java:1795) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIViewRoot._process(UIViewRoot.java:1653) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:909) ~[myfaces-api-2.2.3.jar:2.2.3]
	at org.apache.myfaces.lifecycle.ProcessValidationsExecutor.execute(ProcessValidationsExecutor.java:38) ~[myfaces-impl-2.2.3.jar:2.2.3]
	at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:196) [myfaces-impl-2.2.3.jar:2.2.3]
	at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:143) [myfaces-impl-2.2.3.jar:2.2.3]
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:198) [myfaces-api-2.2.3.jar:2.2.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.47]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) [tomcat7-websocket.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [catalina.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.47]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:67) [log4j-web-2.0.2.jar:2.0.2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [catalina.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.47]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.47]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.47]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [catalina.jar:7.0.47]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.47]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100) [catalina.jar:7.0.47]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953) [catalina.jar:7.0.47]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.47]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [catalina.jar:7.0.47]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041) [tomcat-coyote.jar:7.0.47]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603) [tomcat-coyote.jar:7.0.47]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310) [tomcat-coyote.jar:7.0.47]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: javax.el.ELException: Error reading 'editable' on type org.pivot4j.analytics.ui.ViewHandler
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:98) ~[el-api.jar:2.2.FR]
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:67) ~[el-api.jar:2.2.FR]
	at org.apache.myfaces.el.unified.resolver.FacesCompositeELResolver.getValue(FacesCompositeELResolver.java:179) ~[myfaces-impl-2.2.3.jar:2.2.3]
	at org.apache.el.parser.AstValue.getValue(AstValue.java:183) ~[jasper-el.jar:7.0.47]
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:185) ~[jasper-el.jar:7.0.47]
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:96) ~[myfaces-impl-2.2.3.jar:2.2.3]
	... 43 more
Caused by: java.lang.NullPointerException
	at org.pivot4j.analytics.ui.ViewHandler.isEditable(ViewHandler.java:804) ~[ViewHandler.class:?]
	at sun.reflect.GeneratedMethodAccessor89.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:87) ~[el-api.jar:2.2.FR]
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:67) ~[el-api.jar:2.2.FR]
	at org.apache.myfaces.el.unified.resolver.FacesCompositeELResolver.getValue(FacesCompositeELResolver.java:179) ~[myfaces-impl-2.2.3.jar:2.2.3]
	at org.apache.el.parser.AstValue.getValue(AstValue.java:183) ~[jasper-el.jar:7.0.47]
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:185) ~[jasper-el.jar:7.0.47]
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:96) ~[myfaces-impl-2.2.3.jar:2.2.3]
	... 43 more
16:21:22.645 ERROR [Pivot4JExceptionHandler] - Unhandled exception has occurred
org.apache.myfaces.view.facelets.el.ContextAwareELException: javax.el.ELException: Error reading 'editable' on type org.pivot4j.analytics.ui.ViewHandler
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:104) ~[myfaces-impl-2.2.3.jar:2.2.3]
	at javax.faces.component._DeltaStateHelper.eval(_DeltaStateHelper.java:377) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponentBase.isRendered(UIComponentBase.java:1211) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponent.isVisitable(UIComponent.java:348) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1011) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191) ~[myfaces-api-2.2.3.jar:2.2.3]
	at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartialExecute(PartialViewContextImpl.java:430) ~[myfaces-impl-2.2.3.jar:2.2.3]
	at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:411) ~[myfaces-impl-2.2.3.jar:2.2.3]
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:60) ~[primefaces-5.3.jar:5.3]
	at javax.faces.component.UIViewRoot$UpdateModelPhaseProcessor.process(UIViewRoot.java:1821) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIViewRoot._process(UIViewRoot.java:1653) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIViewRoot.processUpdates(UIViewRoot.java:916) ~[myfaces-api-2.2.3.jar:2.2.3]
	at org.apache.myfaces.lifecycle.UpdateModelValuesExecutor.execute(UpdateModelValuesExecutor.java:38) ~[myfaces-impl-2.2.3.jar:2.2.3]
	at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:196) [myfaces-impl-2.2.3.jar:2.2.3]
	at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:143) [myfaces-impl-2.2.3.jar:2.2.3]
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:198) [myfaces-api-2.2.3.jar:2.2.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.47]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) [tomcat7-websocket.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [catalina.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.47]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:67) [log4j-web-2.0.2.jar:2.0.2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [catalina.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.47]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.47]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.47]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [catalina.jar:7.0.47]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.47]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100) [catalina.jar:7.0.47]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953) [catalina.jar:7.0.47]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.47]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [catalina.jar:7.0.47]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041) [tomcat-coyote.jar:7.0.47]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603) [tomcat-coyote.jar:7.0.47]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310) [tomcat-coyote.jar:7.0.47]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: javax.el.ELException: Error reading 'editable' on type org.pivot4j.analytics.ui.ViewHandler
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:98) ~[el-api.jar:2.2.FR]
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:67) ~[el-api.jar:2.2.FR]
	at org.apache.myfaces.el.unified.resolver.FacesCompositeELResolver.getValue(FacesCompositeELResolver.java:179) ~[myfaces-impl-2.2.3.jar:2.2.3]
	at org.apache.el.parser.AstValue.getValue(AstValue.java:183) ~[jasper-el.jar:7.0.47]
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:185) ~[jasper-el.jar:7.0.47]
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:96) ~[myfaces-impl-2.2.3.jar:2.2.3]
	... 43 more
Caused by: java.lang.NullPointerException
	at org.pivot4j.analytics.ui.ViewHandler.isEditable(ViewHandler.java:804) ~[ViewHandler.class:?]
	at sun.reflect.GeneratedMethodAccessor89.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:87) ~[el-api.jar:2.2.FR]
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:67) ~[el-api.jar:2.2.FR]
	at org.apache.myfaces.el.unified.resolver.FacesCompositeELResolver.getValue(FacesCompositeELResolver.java:179) ~[myfaces-impl-2.2.3.jar:2.2.3]
	at org.apache.el.parser.AstValue.getValue(AstValue.java:183) ~[jasper-el.jar:7.0.47]
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:185) ~[jasper-el.jar:7.0.47]
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:96) ~[myfaces-impl-2.2.3.jar:2.2.3]
	... 43 more

**Comment by GisDeng** [comment]
I've already solved it，This project lacks 3 Java classes in org.pivot4j.mdx.impl. I had down this class in the http://www.pivot4j.org/. and it runs

**Comment by GisDeng** [comment]
I hava  another bug

09:57:52.458 ERROR [Pivot4JExceptionHandler] - Unhandled exception has occurred
org.apache.myfaces.view.facelets.el.ContextAwareELException: javax.el.ELException: Error reading 'editable' on type org.pivot4j.analytics.ui.ViewHandler
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:104) ~[myfaces-impl-2.2.3.jar:2.2.3]
	at javax.faces.component._DeltaStateHelper.eval(_DeltaStateHelper.java:377) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponentBase.isRendered(UIComponentBase.java:1211) ~[myfaces-api-2.2.3.jar:2.2.3]
	at org.primefaces.extensions.component.layout.LayoutPaneRenderer.encodeBegin(LayoutPaneRenderer.java:63) ~[primefaces-extensions-4.0.0.jar:4.0.0]
	at javax.faces.component.UIComponentBase.encodeBegin(UIComponentBase.java:596) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:526) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:550) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:550) ~[myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:550) ~[myfaces-api-2.2.3.jar:2.2.3]
	at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.renderView(FaceletViewDeclarationLanguage.java:1891) ~[myfaces-impl-2.2.3.jar:2.2.3]
	at org.apache.myfaces.application.ViewHandlerImpl.renderView(ViewHandlerImpl.java:313) ~[myfaces-impl-2.2.3.jar:2.2.3]
	at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:116) ~[myfaces-impl-2.2.3.jar:2.2.3]
	at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:267) [myfaces-impl-2.2.3.jar:2.2.3]
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:200) [myfaces-api-2.2.3.jar:2.2.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.47]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) [tomcat7-websocket.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [catalina.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.47]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:67) [log4j-web-2.0.2.jar:2.0.2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [catalina.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.47]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.47]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.47]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [catalina.jar:7.0.47]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.47]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100) [catalina.jar:7.0.47]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953) [catalina.jar:7.0.47]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.47]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [catalina.jar:7.0.47]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041) [tomcat-coyote.jar:7.0.47]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603) [tomcat-coyote.jar:7.0.47]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote.jar:7.0.47]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: javax.el.ELException: Error reading 'editable' on type org.pivot4j.analytics.ui.ViewHandler
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:98) ~[el-api.jar:2.2.FR]
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:67) ~[el-api.jar:2.2.FR]
	at org.apache.myfaces.el.unified.resolver.FacesCompositeELResolver.getValue(FacesCompositeELResolver.java:179) ~[myfaces-impl-2.2.3.jar:2.2.3]
	at org.apache.el.parser.AstValue.getValue(AstValue.java:183) ~[jasper-el.jar:7.0.47]
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:185) ~[jasper-el.jar:7.0.47]
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:96) ~[myfaces-impl-2.2.3.jar:2.2.3]
	... 35 more
Caused by: java.lang.NullPointerException
	at org.pivot4j.analytics.ui.ViewHandler.isEditable(ViewHandler.java:804) ~[ViewHandler.class:?]
	at sun.reflect.GeneratedMethodAccessor85.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:87) ~[el-api.jar:2.2.FR]
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:67) ~[el-api.jar:2.2.FR]
	at org.apache.myfaces.el.unified.resolver.FacesCompositeELResolver.getValue(FacesCompositeELResolver.java:179) ~[myfaces-impl-2.2.3.jar:2.2.3]
	at org.apache.el.parser.AstValue.getValue(AstValue.java:183) ~[jasper-el.jar:7.0.47]
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:185) ~[jasper-el.jar:7.0.47]
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:96) ~[myfaces-impl-2.2.3.jar:2.2.3]
	... 35 more
