### ISSUE TITLE
Issue with LocaleInitializer.afterPhase

### ISSUE THREAD

**Issue by MANUVILAKUNNATHU** [mysticfall/pivot4j#237]
when running the application the below given error is repeatedly printing in the console .
console log
15:25:10.103 ERROR [Pivot4JExceptionHandler] - Unhandled exception has occurred
java.lang.NullPointerException
	at org.pivot4j.analytics.listener.LocaleInitializer.afterPhase(LocaleInitializer.java:57) ~[classes/:?]
	at org.apache.myfaces.lifecycle.PhaseListenerManager.informPhaseListenersAfter(PhaseListenerManager.java:117) ~[myfaces-impl-2.2.3.jar:2.2.3]
	at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:211) [myfaces-impl-2.2.3.jar:2.2.3]
	at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:143) [myfaces-impl-2.2.3.jar:2.2.3]
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:198) [myfaces-api-2.2.3.jar:2.2.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290) [catalina-6.0.29.jar:6.0.29]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina-6.0.29.jar:6.0.29]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:67) [log4j-web-2.0.2.jar:2.0.2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235) [catalina-6.0.29.jar:6.0.29]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina-6.0.29.jar:6.0.29]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233) [catalina-6.0.29.jar:6.0.29]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191) [catalina-6.0.29.jar:6.0.29]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127) [catalina-6.0.29.jar:6.0.29]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) [catalina-6.0.29.jar:6.0.29]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) [catalina-6.0.29.jar:6.0.29]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298) [catalina-6.0.29.jar:6.0.29]
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:857) [coyote-6.0.29.jar:6.0.29]
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588) [coyote-6.0.29.jar:6.0.29]
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489) [coyote-6.0.29.jar:6.0.29]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by GisDeng** [comment]
I've already solved it，This project lacks 3 Java classes in org.pivot4j.mdx.impl. I had down this class in the http://www.pivot4j.org/. and it runs

**Comment by MANUVILAKUNNATHU** [comment]
I've copied the three java classes namely CupParser.java,Symbols.java,Yylex.java to org.pivot4j.mdx.impl but when building am getting an error that says duplicate class decleration.
when I went to the folder I can see that in the target directory 'target/generated-sources/parser/org/pivot4j/mdx/impl' contains the same classes.

**console log**


[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project pivot4j-core: Compilation failure: Compilation failure:
[ERROR] /usr/local/AT_Dev_Env/Pivot4j_Code/pivot/pivot4j-master/pivot4j-core/src/main/java/org/pivot4j/mdx/impl/CupParser.java:[22,8] duplicate class: org.pivot4j.mdx.impl.CupParser
[ERROR] /usr/local/AT_Dev_Env/Pivot4j_Code/pivot/pivot4j-master/pivot4j-core/src/main/java/org/pivot4j/mdx/impl/CupParser.java:[672,1] duplicate class: org.pivot4j.mdx.impl.CUP$CupParser$actions
[ERROR] /usr/local/AT_Dev_Env/Pivot4j_Code/pivot/pivot4j-master/pivot4j-core/target/generated-sources/parser/org/pivot4j/mdx/impl/Symbols.java:[10,8] duplicate class: org.pivot4j.mdx.impl.Symbols
[ERROR] /usr/local/AT_Dev_Env/Pivot4j_Code/pivot/pivot4j-master/pivot4j-core/src/main/java/org/pivot4j/mdx/impl/Yylex.java:[26,8] duplicate class: org.pivot4j.mdx.impl.Yylex

**Comment by GisDeng** [comment]
maybe you should update your maven project, and maybe some jar packages download failured, you need to download manually.
