### ISSUE TITLE
Pivot4j is Not Running Please help

### ISSUE THREAD

**Issue by Aman9407555** [mysticfall/pivot4j#239]
I am not able to run pivot4j ,I am getting this Logs please help:

mondrian.olap.MondrianException: Mondrian Error:Internal error: Error while creating SQL connection: Jdbc=jdbc:derby:E:\SELF_LEARNING\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\pivot4j-analytics\WEB-INF\foodmart; JdbcUser=sa
	at mondrian.resource.MondrianResource$_Def0.ex(MondrianResource.java:987) ~[mondrian-3.12.0.19-384.jar:?]
	at mondrian.olap.Util.newInternal(Util.java:2410) ~[mondrian-3.12.0.19-384.jar:3.12.0.19-384]
	at mondrian.olap.Util.newError(Util.java:2426) ~[mondrian-3.12.0.19-384.jar:3.12.0.19-384]
	at mondrian.rolap.RolapConnection.<init>(RolapConnection.java:247) ~[mondrian-3.12.0.19-384.jar:?]
	at mondrian.rolap.RolapSchema.<init>(RolapSchema.java:188) ~[mondrian-3.12.0.19-384.jar:?]
	at mondrian.rolap.RolapSchema.<init>(RolapSchema.java:216) ~[mondrian-3.12.0.19-384.jar:?]
	at mondrian.rolap.RolapSchemaPool.createRolapSchema(RolapSchemaPool.java:294) ~[mondrian-3.12.0.19-384.jar:?]
	at mondrian.rolap.RolapSchemaPool.getByKey(RolapSchemaPool.java:227) ~[mondrian-3.12.0.19-384.jar:?]
	at mondrian.rolap.RolapSchemaPool.get(RolapSchemaPool.java:166) ~[mondrian-3.12.0.19-384.jar:?]
	at mondrian.rolap.RolapSchemaPool.get(RolapSchemaPool.java:72) ~[mondrian-3.12.0.19-384.jar:?]
	at mondrian.rolap.RolapConnection.<init>(RolapConnection.java:161) ~[mondrian-3.12.0.19-384.jar:?]
	at mondrian.rolap.RolapConnection.<init>(RolapConnection.java:91) ~[mondrian-3.12.0.19-384.jar:?]
	at mondrian.olap.DriverManager.getConnection(DriverManager.java:113) ~[mondrian-3.12.0.19-384.jar:3.12.0.19-384]
	at mondrian.olap.DriverManager.getConnection(DriverManager.java:69) ~[mondrian-3.12.0.19-384.jar:3.12.0.19-384]
	at mondrian.olap4j.MondrianOlap4jConnection.<init>(MondrianOlap4jConnection.java:162) ~[mondrian-3.12.0.19-384.jar:?]
	at mondrian.olap4j.FactoryJdbc4Plus$AbstractConnection.<init>(FactoryJdbc4Plus.java:323) ~[mondrian-3.12.0.19-384.jar:?]
	at mondrian.olap4j.FactoryJdbc41Impl$MondrianOlap4jConnectionJdbc41.<init>(FactoryJdbc41Impl.java:118) ~[mondrian-3.12.0.19-384.jar:?]
	at mondrian.olap4j.FactoryJdbc41Impl.newConnection(FactoryJdbc41Impl.java:32) ~[mondrian-3.12.0.19-384.jar:?]
	at mondrian.olap4j.MondrianOlap4jDriver.connect(MondrianOlap4jDriver.java:97) ~[mondrian-3.12.0.19-384.jar:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_131]
	at java.sql.DriverManager.getConnection(DriverManager.java:208) ~[?:1.8.0_131]
	at org.pivot4j.datasource.SimpleOlapDataSource.createConnection(SimpleOlapDataSource.java:75) ~[pivot4j-core-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
	at org.pivot4j.datasource.AbstractOlapDataSource.getConnection(AbstractOlapDataSource.java:105) ~[pivot4j-core-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
	at org.pivot4j.datasource.AbstractOlapDataSource.getConnection(AbstractOlapDataSource.java:95) ~[pivot4j-core-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
	at org.pivot4j.analytics.datasource.simple.SimpleDataSourceManager.getCubes(SimpleDataSourceManager.java:124) ~[classes/:?]
	at org.pivot4j.analytics.ui.CatalogChooser.getCubes(CatalogChooser.java:117) [classes/:?]
	at org.pivot4j.analytics.ui.CatalogChooser.onCatalogChanged(CatalogChooser.java:152) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.apache.el.parser.AstValue.invoke(AstValue.java:247) [jasper-el.jar:8.0.44]
	at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267) [jasper-el.jar:8.0.44]
	at org.apache.myfaces.view.facelets.el.ContextAwareTagMethodExpression.invoke(ContextAwareTagMethodExpression.java:96) [myfaces-impl-2.2.3.jar:2.2.3]
	at org.primefaces.behavior.ajax.AjaxBehaviorListenerImpl.processAjaxBehavior(AjaxBehaviorListenerImpl.java:54) [primefaces-5.3.jar:5.3]
	at javax.faces.event.AjaxBehaviorEvent.processListener(AjaxBehaviorEvent.java:54) [myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.behavior.BehaviorBase.broadcast(BehaviorBase.java:70) [myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIComponentBase.broadcast(UIComponentBase.java:415) [myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIInput.broadcast(UIInput.java:359) [myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIViewRoot._broadcastAll(UIViewRoot.java:1172) [myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:365) [myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIViewRoot._process(UIViewRoot.java:1656) [myfaces-api-2.2.3.jar:2.2.3]
	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:862) [myfaces-api-2.2.3.jar:2.2.3]
	at org.apache.myfaces.lifecycle.InvokeApplicationExecutor.execute(InvokeApplicationExecutor.java:42) [myfaces-impl-2.2.3.jar:2.2.3]
	at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:196) [myfaces-impl-2.2.3.jar:2.2.3]
	at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:143) [myfaces-impl-2.2.3.jar:2.2.3]
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:198) [myfaces-api-2.2.3.jar:2.2.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292) [catalina.jar:8.0.44]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.44]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.44]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.44]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.44]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:67) [log4j-web-2.0.2.jar:2.0.2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.44]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.44]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) [catalina.jar:8.0.44]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94) [catalina.jar:8.0.44]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504) [catalina.jar:8.0.44]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [catalina.jar:8.0.44]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.44]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620) [catalina.jar:8.0.44]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.44]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502) [catalina.jar:8.0.44]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132) [tomcat-coyote.jar:8.0.44]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684) [tomcat-coyote.jar:8.0.44]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1533) [tomcat-coyote.jar:8.0.44]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1489) [tomcat-coyote.jar:8.0.44]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.44]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.sql.SQLException: Database 'E:\SELF_LEARNING\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\pivot4j-analytics\WEB-INF\foodmart' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source) ~[derby-10.10.2.0.jar:?]
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source) ~[derby-10.10.2.0.jar:?]
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source) ~[derby-10.10.2.0.jar:?]
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source) ~[derby-10.10.2.0.jar:?]
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source) ~[derby-10.10.2.0.jar:?]
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source) ~[derby-10.10.2.0.jar:?]
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source) ~[derby-10.10.2.0.jar:?]
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source) ~[derby-10.10.2.0.jar:?]
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source) ~[derby-10.10.2.0.jar:?]
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source) ~[derby-10.10.2.0.jar:?]
	at org.apache.derby.jdbc.Driver20.connect(Unknown Source) ~[derby-10.10.2.0.jar:?]
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source) ~[derby-10.10.2.0.jar:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_131]
	at java.sql.DriverManager.getConnection(DriverManager.java:208) ~[?:1.8.0_131]
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:51) ~[commons-dbcp-1.2.1.jar:1.2.1]
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:290) ~[commons-dbcp-1.2.1.jar:1.2.1]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1188) ~[commons-pool-1.6.jar:1.6]
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:95) ~[commons-dbcp-1.2.1.jar:1.2.1]
	at mondrian.rolap.RolapConnection.<init>(RolapConnection.java:227) ~[mondrian-3.12.0.19-384.jar:?]
	... 67 more
Caused by: org.apache.derby.impl.jdbc.EmbedSQLException: Database 'E:\SELF_LEARNING\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\pivot4j-analytics\WEB-INF\foodmart' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source) ~[derby-10.10.2.0.jar:?]
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source) ~[derby-10.10.2.0.jar:?]
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source) ~[derby-10.10.2.0.jar:?]
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source) ~[derby-10.10.2.0.jar:?]
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source) ~[derby-10.10.2.0.jar:?]
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source) ~[derby-10.10.2.0.jar:?]
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source) ~[derby-10.10.2.0.jar:?]
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source) ~[derby-10.10.2.0.jar:?]
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source) ~[derby-10.10.2.0.jar:?]
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source) ~[derby-10.10.2.0.jar:?]
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source) ~[derby-10.10.2.0.jar:?]
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source) ~[derby-10.10.2.0.jar:?]
	at org.apache.derby.jdbc.Driver20.connect(Unknown Source) ~[derby-10.10.2.0.jar:?]
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source) ~[derby-10.10.2.0.jar:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_131]
	at java.sql.DriverManager.getConnection(DriverManager.java:208) ~[?:1.8.0_131]
	at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:51) ~[commons-dbcp-1.2.1.jar:1.2.1]
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:290) ~[commons-dbcp-1.2.1.jar:1.2.1]
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1188) ~[commons-pool-1.6.jar:1.6]
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:95) ~[commons-dbcp-1.2.1.jar:1.2.1]
	at mondrian.rolap.RolapConnection.<init>(RolapConnection.java:227) ~[mondrian-3.12.0.19-384.jar:?]
	... 67 more
![image](https://user-images.githubusercontent.com/32872558/42021240-b88629d8-7ad7-11e8-82f0-1b830265b5ee.png)

**Comment by Judilson** [comment]
This problem 'E:\SELF_LEARNING.metadata.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\pivot4j-analytics\WEB-INF\foodmart' not found.

**Comment by Aman9407555** [comment]
@Judilson 
but that file is already there

**Comment by ShengtianM** [comment]
You can use your own datasource, the configuration file path is /WEB-INF/pivot4j-config.xml,  just like
![image](https://user-images.githubusercontent.com/7629070/43436271-3f65ea90-94b6-11e8-9d4c-424a0fe851eb.png), the bank.xml is a schema file.
